=== EiffelSoftware/traffic/example/em/city_timetable/schedule.dtd
<!ELEMENT slines (sline+)> 

<!ELEMENT sline (entry+)> 
<!ATTLIST sline     
	name CDATA #REQUIRED  
    >    
<!ELEMENT entry EMPTY> 
<!ATTLIST entry     
	station CDATA #REQUIRED 
	arrival CDATA #REQUIRED    
    	departure CDATA #REQUIRED
	>

=== EiffelSoftware/traffic/example/city_timetable/timetable_tram.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE slines SYSTEM "schedule.dtd">

<slines>

<sline name="Linie4">
<entry station="Werdhoelzli" arrival="0" departure="0"/>
<entry station="Baendliweg" arrival="2" departure="3"/>
<entry station="Gruenaustrasse" arrival="4" departure="5"/>
</sline>

<sline name="Linie13">
<entry station="Frankental" arrival="0" departure="0"/>
<entry station="Wartau" arrival="2" departure="3"/>
<entry station="Zwielplatz" arrival="4" departure="5"/>
</sline>

</slines>
