=== EiffelSoftware/traffic/examples/map/city.dtd
<!--- A city has a name and contains stations and lines. --> 
<!ELEMENT city (station*,line*)> 
<!ATTLIST city
	name CDATA #REQUIRED
    >   
 
<!--- A station has a name and two coordinates: x and y. --> 
<!ELEMENT station EMPTY> 
<!ATTLIST station
	name CDATA #REQUIRED     
	y CDATA #REQUIRED     
	x CDATA #REQUIRED   
    >    
    
<!--- A transportation kind has a name, a default color and possibly and icon. --> 
<!ELEMENT transport EMPTY> 
<!ATTLIST transport
	name CDATA #REQUIRED     
	color CDATA #REQUIRED     
	icon CDATA #IMPLIED   
    >    

<!--- A line has a name and type and contains stops. --> 
<!ELEMENT line (stop*)> 
<!ATTLIST line     
	name CDATA #REQUIRED
	kind CDATA #REQUIRED
   	>  

<!--- A stop has a name. --> 
<!ELEMENT stop EMPTY> 
<!ATTLIST stop
	name CDATA #REQUIRED     
    >

=== EiffelSoftware/traffic/examples/test/zurich.xml
<?xml version="1.0"?>

<!DOCTYPE city SYSTEM "city.dtd">

<city name="Zurich">

	<station name="Central" x="100.0" y="0.0"/>
	<station name="Bahnhofplatz/HB" x="-200.0" y="0.0"/>
	<station name="Bahnhofstrasse/HB" x="-100.0" y="-50.0"/>
	<station name="Bahnhofquai/HB" x="-100.0" y="100.0"/>
	<station name="Haldenegg" x="300.0" y="200.0"/>
	<station name="ETH/Universitaetsspital" x="500.0" y="50.0"/>
	<station name="Sonneggstrasse" x="300.0" y="400.0"/>
	<station name="Rudolf-Brun-Bruecke" x="100.0" y="-100.0"/>

	<line name="4" kind="tram">
		<stop name="Bahnhofquai/HB"/>
		<stop name="Central"/>
		<stop name="Rudolf-Brun-Bruecke"/>
	</line>
	<line name="6" kind="tram">
		<stop name="Bahnhofstrasse/HB"/>
		<stop name="Central"/>
		<stop name="Haldenegg"/>
		<stop name="ETH/Universitaetsspital"/>		
	</line>
	<line name="7" kind="tram">
		<stop name="Bahnhofstrasse/HB"/>
		<stop name="Central"/>
		<stop name="Haldenegg"/>
		<stop name="Sonneggstrasse"/>		
	</line>
	<line name="10" kind="tram">
		<stop name="Bahnhofplatz/HB"/>
		<stop name="Central"/>
		<stop name="Haldenegg"/>
		<stop name="ETH/Universitaetsspital"/>		
	</line>
	<line name="15" kind="tram">
		<stop name="Rudolf-Brun-Bruecke"/>
		<stop name="Central"/>
		<stop name="Haldenegg"/>
		<stop name="Sonneggstrasse"/>		
	</line>
	
</city>
