=== EiffelSoftware/traffic/example/city_3d/map_new.dtd
<?xml version='1.0' encoding='UTF-8'?>  
<!--     An example how to use this DTD from your XML document:     
<?xml version="1.0"?>     
<!DOCTYPE map SYSTEM "map_simple_application.dtd">     
<map>
...
</map> -->

<!--- description. --> 
<!ELEMENT description EMPTY> 
<!ATTLIST description 
	text CDATA #REQUIRED
    >

<!--- A Map can have places and links. --> 
<!ELEMENT map (description, places, lines)> 
<!ATTLIST map
	name   CDATA #IMPLIED
    >   
 
<!--- A Point must have two coordinates: x and y. --> 
<!ELEMENT point EMPTY> 
<!ATTLIST point     
	y CDATA #REQUIRED     
	x CDATA #REQUIRED   
    >    

<!--- File. --> 
<!ELEMENT file EMPTY> 
<!ATTLIST file     
	name CDATA #REQUIRED     
    >  

<!--- A Color consists of 3 RGB-components and its use. --> 
<!ELEMENT color EMPTY> 
<!ATTLIST color     
	blue  CDATA #REQUIRED     
	green CDATA #REQUIRED     
	red   CDATA #REQUIRED     
   >    

<!--- Places can be stops, landmarks... --> 
<!ELEMENT places (place*)>   

<!--- A place must have a name and a point. --> 
<!ELEMENT place (file*,description?)> 
<!ATTLIST place     
	name CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
   >  

<!--- Lines. --> 
<!ELEMENT lines (line*)>   

<!--- A line must have a name. --> 
<!ELEMENT line (color?, line_section*)> 
<!ATTLIST line     
	name   CDATA #REQUIRED
	type   CDATA #REQUIRED
	simple (true | false) "false"
   >  

<!--- Line sections connect places.  -->
<!ELEMENT line_section (point,point+)>  

<!ATTLIST line_section     
	from CDATA #REQUIRED
	to CDATA #REQUIRED     
	direction (directed | undirected) "directed"
  >

=== EiffelSoftware/traffic/example/flat_hunt/map/zurich_little.xml
<?xml version="1.0"?>
<!DOCTYPE city SYSTEM "map_new.dtd"> 
<map name="Zurich (little)"> 

<description text="kleine zurich city map."/>

<places>

	<place name="Bahnhof Stadelhofen" x="" y="">
		<file name="some_file_name"/>
		<file name="some_other_file_name"/>
		<description text="one of many stations in zurich"/>
	</place>
	<place name="Bellevue"/>
	<place name="Boersenstrasse"/>
	<place name="Buerkliplatz"/>
	<place name="Central"/>
	<place name="Hauptbahnhof"/>
	<place name="Helmhaus"/>
	<place name="Kunsthaus"/>
	<place name="Neumarkt"/>
	<place name="Paradeplatz"/>
	<place name="Rennweg"/>
	<place name="Rathaus"/>
	<place name="Rudolf-Brun-Bruecke"/>

</places>

<lines>


<!-- tram lines -->

<line name="11" type="tram">
	<color red="0" green="154" blue="0"/>
	<line_section from="Bahnhof Stadelhofen" to="Bellevue" direction="undirected">
		        <point x="910" y="495"/>
		        <point x="843" y="495"/>
	</line_section>
	<line_section from="Bellevue" to="Buerkliplatz" direction="undirected">
		        <point x="843" y="495"/>
		        <point x="750" y="495"/>
	</line_section>
	<line_section from="Buerkliplatz" to="Boersenstrasse" direction="undirected">
		        <point x="750" y="495"/>
		        <point x="735" y="495"/>
		        <point x="710" y="520"/>
	</line_section>
	<line_section from="Boersenstrasse" to="Paradeplatz" direction="undirected">
		        <point x="710" y="520"/> 
		        <point x="660" y="570"/>
	</line_section>
	<line_section from="Paradeplatz" to="Rennweg" direction="undirected">
		        <point x="660" y="570"/>
		        <point x="705" y="615"/>
		        <point x="705" y="655"/>
	</line_section>
	<line_section from="Rennweg" to="Hauptbahnhof" direction="undirected">
		        <point x="705" y="655"/>
		        <point x="705" y="835"/>
	</line_section>
</line>


<line name="9" type="tram">
	<color red="102" green="102" blue="153"/>
	<line_section from="Paradeplatz" to="Boersenstrasse" direction="undirected">
		        <point x="660" y="600"/> 
		        <point x="740" y="520"/>
	</line_section>
	<line_section from="Boersenstrasse" to="Buerkliplatz" direction="undirected">
		        <point x="740" y="520"/>
		        <point x="744" y="515"/>
		        <point x="750" y="515"/> 
	</line_section>
	<line_section from="Buerkliplatz" to="Bellevue" direction="undirected">
		        <point x="750" y="515"/> 
		        <point x="820" y="515"/>
		        <point x="843" y="540"/>	   
	</line_section>
	<line_section from="Bellevue" to="Kunsthaus" direction="undirected">
		        <point x="843" y="540"/> 
		        <point x="940" y="638"/> 
	</line_section>
</line>


<line name="4" type="tram">
	<color red="90" green="90" blue="143"/> 
	<line_section from="Hauptbahnhof" to="Central" direction="undirected">
		        <point x="715" y="830"/>
		        <point x="715" y="780"/>
		        <point x="810" y="780"/>
	</line_section>
	<line_section from="Central" to="Rudolf-Brun-Bruecke" direction="undirected">
		        <point x="810" y="780"/>
		        <point x="810" y="655"/>
	</line_section>
	<line_section from="Rudolf-Brun-Bruecke" to="Rathaus" direction="undirected">
		        <point x="810" y="655"/>
		        <point x="810" y="620"/>
	</line_section>
	<line_section from="Rathaus" to="Helmhaus" direction="undirected">
		        <point x="810" y="620"/>
		        <point x="810" y="583"/>
	</line_section>
	<line_section from="Helmhaus" to="Bellevue" direction="undirected">
		        <point x="810" y="583"/>
		        <point x="810" y="547"/>
		        <point x="843" y="515"/>
	</line_section>
</line>

<!-- bus lines -->
<line name="31" type="bus">
	<color red="153" green="204" blue="255"/>
	<line_section from="Kunsthaus" to="Neumarkt" direction="undirected">
			<point x="934" y="617"/>
			<point x="880" y="671"/>
	</line_section>
	<line_section from="Neumarkt" to="Central" direction="undirected">
			<point x="880" y="671"/>
			<point x="833" y="718"/>
	</line_section>
	<line_section from="Central" to="Hauptbahnhof" direction="undirected">
			<point x="833" y="718"/>
			<point x="681" y="718"/>
	</line_section>
</line> 


<!-- s lines -->
<line name="s7" type="rail">
	<color red="0" green="0" blue="0"/>
	<line_section from="Hauptbahnhof" to="Bahnhof Stadelhofen" direction="undirected">
			<point x="693" y="833"/>
			<point x="811" y="833"/>
			<point x="822" y="831"/>
			<point x="831" y="827"/>
			<point x="839" y="822"/>
			<point x="846" y="814"/>
			<point x="851" y="802"/>
			<point x="853" y="792"/>
			<point x="853" y="785"/>
			<point x="853" y="569"/>
			<point x="854" y="563"/>
			<point x="859" y="557"/>
			<point x="862" y="550"/>
			<point x="902" y="510"/>
	</line_section>
</line>

</lines>

</map>
